"""Centralized figure styling so every paper figure is consistent and accessible.

All figures are generated by scripts from tracked inputs and saved with stable
filenames (CLAUDE.md, "Figures should be reproducible"). The default categorical
palette is the Okabe-Ito set, which is distinguishable under the common forms of
color-vision deficiency; diverging/sequential maps are colorblind-safe as well. Use
these helpers rather than ad-hoc matplotlib colors so accessibility is not optional.
"""
from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from matplotlib.colors import Colormap
    from matplotlib.figure import Figure

# Okabe & Ito (2008) qualitative palette: 8 colors that stay distinct under
# deuteranopia / protanopia / tritanopia. Order chosen for high pairwise contrast.
OKABE_ITO: tuple[str, ...] = (
    "#0072B2",  # blue
    "#D55E00",  # vermillion
    "#009E73",  # bluish green
    "#CC79A7",  # reddish purple
    "#E69F00",  # orange
    "#56B4E9",  # sky blue
    "#F0E442",  # yellow
    "#000000",  # black
)


def palette(n: int) -> list[str]:
    """First ``n`` Okabe-Ito colors, cycling if ``n`` exceeds the palette length."""
    if n <= 0:
        return []
    return [OKABE_ITO[i % len(OKABE_ITO)] for i in range(n)]


def apply_publication_style() -> None:
    """Set matplotlib rcParams for publication figures (fonts, sizes, the palette).

    Idempotent; call once at the top of a figure script. Vector-friendly defaults
    (TrueType fonts embedded) so PDFs are editable in a paper toolchain.
    """
    import matplotlib as mpl
    from cycler import cycler

    mpl.rcParams.update(
        {
            "figure.dpi": 150,
            "savefig.dpi": 300,
            "savefig.bbox": "tight",
            "font.size": 11,
            "axes.titlesize": 12,
            "axes.labelsize": 11,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.prop_cycle": cycler(color=list(OKABE_ITO)),
            "axes.grid": True,
            "grid.alpha": 0.3,
            "grid.linewidth": 0.5,
            "legend.frameon": False,
            "pdf.fonttype": 42,  # embed TrueType (editable text in PDF)
            "ps.fonttype": 42,
        }
    )


def sequential_cmap() -> "Colormap":
    """A perceptually-uniform, colorblind-safe sequential colormap (viridis)."""
    import matplotlib.cm as cm

    return cm.get_cmap("viridis")


def diverging_cmap() -> "Colormap":
    """A colorblind-safe diverging colormap for signed effects (blue-white-orange)."""
    import matplotlib.cm as cm

    # 'coolwarm' reads as blue<->red (problematic); use a blue/orange diverging map.
    return cm.get_cmap("PuOr")


def save_figure(fig: "Figure", path: str | Path, formats: tuple[str, ...] = ("png", "pdf"), **kwargs: Any) -> list[Path]:
    """Save a figure to multiple formats with a stable stem; return the written paths.

    Always writes a raster (png) for quick viewing and a vector (pdf) for the paper.
    """
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for fmt in formats:
        out = path.with_suffix(f".{fmt}")
        fig.savefig(out, **kwargs)
        written.append(out)
    return written
